<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-secure_workflow_system-13128b7f-40af-4f2f-a722-5d4d240632bc</UserSecretsId>
    <RootNamespace>secure_workflow_system</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".github\bug_report.md" />
    <None Include=".github\CODEOWNERS" />
    <None Include=".github\documentation---style-discussion.md" />
    <None Include=".github\feature_request.md" />
    <None Include=".github\ISSUE_TEMPLATE\bug_report.md" />
    <None Include=".github\ISSUE_TEMPLATE\documentation---style-discussion.md" />
    <None Include=".github\ISSUE_TEMPLATE\feature_request.md" />
    <None Include=".github\ISSUE_TEMPLATE\miscellaneous-issue-template.md" />
    <None Include=".github\ISSUE_TEMPLATE\seed-data---database-change-request.md" />
    <None Include=".github\ISSUE_TEMPLATE\task---work-item.md" />
    <None Include=".github\ISSUE_TEMPLATE\test_qa_task.md" />
    <None Include=".github\miscellaneous-issue-template.md" />
    <None Include=".github\ISSUE_TEMPLATE\follow_up.md" />
    <None Include=".github\pr_template\pull_request_template.md" />
    <None Include=".github\seed-data---database-change-request.md" />
    <None Include=".github\task---work-item.md" />
    <None Include=".github\test---qa-task.md" />
    <None Include=".github\workflows\ci.yml" />
    <None Include=".github\workflows\deploy.yml" />
    <None Include="secure-workflow-system.slnx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include=".github\PR_TEMPLATE\" />
  </ItemGroup>

</Project>
